### ISSUE TITLE
GraphQL query parsing and validation

### ISSUE THREAD

**Issue by sureshHARDIYA** [sureshHARDIYA/phd-resources#8]
GraphQL query parsing and validation

**Comment by ganeshcse2991** [comment]
I have created an [npm module](https://www.npmjs.com/package/validate-graphql) for handling validations in GraphQL in a better way. Please check the [validate-graphql](https://www.npmjs.com/package/validate-graphql) npm package.

**Comment by sureshHARDIYA** [comment]
Thank you @ganeshcse2991  for a suggestion. I will for sure check the NPM package.
